### ISSUE TITLE
Thumbnail issues

### ISSUE THREAD

**Issue by shiva2099** [prgofficial/URLuploader-With-Hotstar#5]
Bro some time thumbnail is not applying in video files bro .
Solve this bro..

**Comment by prgofficial** [comment]
Any error in logs???

**Comment by shiva2099** [comment]
> Any error in logs???

No bro its only issue in video file if we upload 3 file 2 file will not have thumbnail bro

**Comment by shiva2099** [comment]
Bro issues is permanent thumbnail bro .. thumbnail is not saving for permanent

**Comment by prgofficial** [comment]
while uploading together??

**Comment by shiva2099** [comment]
Yes bro and Thumbnail is not saving permanent bro

**Comment by prgofficial** [comment]
Can u deploy and try now??

**Comment by shiva2099** [comment]
![Screenshot_20210206-102454](https://user-images.githubusercontent.com/76653639/107109344-ad18c780-6865-11eb-9f02-547cb7eefcd1.png)
Bro now files is not uploading

**Comment by prgofficial** [comment]
Ok.. 👨‍🦯👨‍🦯 need to run and test it.. will fix be eve

**Comment by prgofficial** [comment]
@shiva2099 deploy and try once👨‍🦯

**Comment by shiva2099** [comment]
> @shiva2099 deploy and try once👨‍🦯

Bro it working fine bro .will it support kintohub .if it support what is start command for that bro .

**Comment by prgofficial** [comment]
Ok..

python3 bot.py   will be the start command
