### ISSUE TITLE
Hotstar errors

### ISSUE THREAD

**Issue by shiva2099** [prgofficial/URLuploader-With-Hotstar#6]
It shows Some errors occured while downloading video!
Hotstar links not able Download bro

**Comment by prgofficial** [comment]
What's the error?? And in which server you running ur app??

**Comment by shiva2099** [comment]
Usa server
![Screenshot_20210207-084438](https://user-images.githubusercontent.com/76653639/107135458-ec581e80-6920-11eb-96db-76749ab66adb.png)

**Comment by prgofficial** [comment]
Then maybe that video cannot be downloaded!  Try with other links..
